### ISSUE TITLE
can't select schema

### ISSUE THREAD

**Issue by szechp** [someone-stole-my-name/yaml-companion.nvim#35]
It seems like I cant get any functionality out of this: I installed the function in lualine to get the schema for the current buffer to debug, but whatever I select with telescope, it always returns none. is there something I forgot? I set it up according to the readme.

**Comment by danielfrg** [comment]
For future reference at the time I write this with the latest versions this is working but the order on how you configure is important because it has a the configs returned by `on_attach` function.

If you are using lspconfig you are probably overwriting this (I was), so i had to move it below. Example: https://github.com/danielfrg/dotfiles/blob/main/nvim/.config/nvim/after/plugin/lsp.lua

**Comment by goodshort** [comment]
Thanks for sharing @danielfrg 
Here is permalink to your [lsp.lua](https://github.com/danielfrg/dotfiles/blob/0e35947fea7566eefc6f4b9fe8488181f6c6ef08/nvim/.config/nvim/after/plugin/lsp.lua) (file changed location in your repo) example above.
